### ISSUE TITLE
Bug relativi al "mangiare una pedina"

### ISSUE THREAD

**Issue by andre-bisa** [AGalassi/TablutCompetition#2]
@AGalassi 
Allego due screenshot per due possibili problemi.
Muovendo la pedina bianca da E3 a A3 ottengo che la pedina nera in posizione A4 viene mangiata (anche se l'accampamento di posizione A5 è coperto da una pedina nera). È un funzionamento corretto? Dalle regole delle slide non è chiaro se questo sia corretto o meno.
![Schermata del 2019-04-08 12-45-08](https://user-images.githubusercontent.com/32579482/55718765-d879c380-59fc-11e9-9af7-f2853d948974.png)

Secondo "problema": se muovo la pedina nera da posizione E2 a E3 NON mangio la pedina bianca in posizione E4, questo è corretto? Dalle regole si evince che il castello "fa da sponda" indipendentemente dal fatto che il re sia dentro o fuori dallo stesso. È corretto? Allego schermata anche di questo.
![Schermata del 2019-04-08 12-45-20](https://user-images.githubusercontent.com/32579482/55718885-20004f80-59fd-11e9-94be-6cf4035fbfe4.png)

**Comment by AGalassi** [comment]
Entrambe le situazioni sono dei bug. Provvederò a correggerle il prima possibile!

**Comment by AGalassi** [comment]
Mi è stata segnalata anche la seguente situazione, in cui piuttosto che una doppia cattura (re in basso e pedina a lato), avviene solo la cattura della pedina laterale.

![image](https://user-images.githubusercontent.com/34279977/55787156-f6efc580-5ab5-11e9-8248-dd6f1664c0d3.png)

**Comment by AGalassi** [comment]
Ora dovrebbe essere corretto

**Comment by GiacomoPinardi** [comment]
Anche dopo l'ultimo aggiornamento non riesco a mangiare la nera (col puntino viola) facendo sponda sull'accampamento (pieno in questo caso, ma dovrebbe valere lo stesso direi (?)). Si tratta di un bug? 

![problema](https://user-images.githubusercontent.com/7230995/56034309-4a1c7f00-5d27-11e9-8696-41dadc43aa3a.png)

**Comment by AGalassi** [comment]
> Anche dopo l'ultimo aggiornamento non riesco a mangiare la pedina nera (col puntino viola) facendo sponda sull'accampamento (pieno in questo caso, ma dovrebbe valere lo stesso direi (?)). Si tratta di un bug?
> 
> ![problema](https://user-images.githubusercontent.com/7230995/56034309-4a1c7f00-5d27-11e9-8696-41dadc43aa3a.png)

Si, dovrebbe essere corretto ora

**Comment by GiacomoPinardi** [comment]
Purtroppo sembra che risolvendo l'ultimo bug si sia ripresentato il primo che e' stato segnalato in questa issue. Allego screenshot:

![first](https://user-images.githubusercontent.com/7230995/56166645-79a4e300-5fd6-11e9-86aa-04f9d5f6c394.png)![second](https://user-images.githubusercontent.com/7230995/56166648-7b6ea680-5fd6-11e9-9cbf-27d510a2fd2c.png)

In viola il riquadro contenente la pedina nera mangiata.

**Comment by AGalassi** [comment]
Dovrebbe essere un bug presente solo in quella citadel lì, adesso dovrebbe essere corretto
