### ISSUE TITLE
Cattura di un pezzo 

### ISSUE THREAD

**Issue by TheLillo** [AGalassi/TablutCompetition#4]
Non ho capito una cosa delle regole: il Trono funge da sponda indipendentemente dal colore della pedina che deve essere mangiata giusto?
L'accampamento invece funge da sponda solo per i Neri che mangiano oppure anche per i Bianchi?

**Comment by AGalassi** [comment]
Sia trono che accampamenti fungono da sponda, indipendentemente dal colore della pedina!

Al momento il motore di gioco ha alcuni bug relativi alle catture, li stiamo correggendo: [#2](https://github.com/AGalassi/TablutCompetition/issues/2)

**Comment by VforV93** [comment]
Aggiungo una domanda inerente alle catture con sponda(trono ed accampamenti).
Il trono funge da sponda per il giocatore di turno indipendentemente dal fatto che sia occupato ancora dal Re?(O funge da sponda per il nero solo se questo è stato abbandonato dal Re?)

Analogamente, gli accampamenti fungono da sponda solo se questi NON sono occupati dal nero oppure indipendentemente da cìò?

**Comment by AGalassi** [comment]
Trono e accampamenti fungono da sponda indipendentemente dal fatto che siano occupati o meno.
Entro la settimana aggiornerò le slide delle regole del gioco in modo da renderle più chiare!
