### ISSUE TITLE
Giocatore Random rimane con una sola pedina: IllegalArgumentException

### ISSUE THREAD

**Issue by GiacomoPinardi** [AGalassi/TablutCompetition#5]
Giocando come giocatore Random alle linee 153 e 239 della classe TablutRandomClient `Random.nextInt` viene chiamato con argomento `pawns.size() - 1` che risulta essere `0` essendoci solo una pedina rimasta.

Questo lancia una `IllegalArgumentException: bound must be positive` che fa perdere la partita al giocatore.

E' un problema secondario, e non relativo alle regole del gioco, ma volevo comunque segnalarlo.
Saluti

**Comment by AGalassi** [comment]
Dovrebbe essere corretto ora
