### ISSUE TITLE
Mangiata re con trono

### ISSUE THREAD

**Issue by mcampestri** [AGalassi/TablutCompetition#7]
Ho notato che nella situazione in figura la mossa del nero C6 -> C5 non provoca la mangiata del re.

![screenshot_1-1](https://user-images.githubusercontent.com/50098999/57111631-2ef8ca00-6d3d-11e9-9ad9-771e248cd355.jpg)
![screenshot_1-2](https://user-images.githubusercontent.com/50098999/57111646-3a4bf580-6d3d-11e9-8703-244003d15449.jpg)

Nel seguente caso invece il re viene mangiato regolarmente.

![screenshot_2-1](https://user-images.githubusercontent.com/50098999/57112230-65cfdf80-6d3f-11e9-91e9-c6a43e43d876.jpg)
![screenshot_2-2](https://user-images.githubusercontent.com/50098999/57112232-69636680-6d3f-11e9-8162-068bbe692533.jpg)

Nel caso fosse utile allego anche i file di log delle due partite.

[gameLog_1.txt](https://github.com/AGalassi/TablutCompetition/files/3140196/gameLog_1.txt)
[gameLog_2.txt](https://github.com/AGalassi/TablutCompetition/files/3140227/gameLog_2.txt)

**Comment by AGalassi** [comment]
Ora dovrebbe essere corretto
