### ISSUE TITLE
Errore cattura del re in F5

### ISSUE THREAD

**Issue by JJonahJson** [AGalassi/TablutCompetition#8]
Con il re in F5, una nera in F4, l'altra in G5 e spostando l'ultima nera da G6 a F6 la cattura del re non viene comunicata e la partita continua, allego i log di seguito.

![image](https://user-images.githubusercontent.com/32750632/57967014-e99de480-7959-11e9-9219-a88ce0328747.png)

[PartitaCompletaServer.txt](https://github.com/AGalassi/TablutCompetition/files/3193845/PartitaCompletaServer.txt)

[1558166254223_systemLog.txt](https://github.com/AGalassi/TablutCompetition/files/3193840/1558166254223_systemLog.txt)

[ErroreSpecificoServer.txt](https://github.com/AGalassi/TablutCompetition/files/3193843/ErroreSpecificoServer.txt)

[MyBlackPlayer.txt](https://github.com/AGalassi/TablutCompetition/files/3193848/MyBlackPlayer.txt)

Specifico che l'errore si è presentato nonostante abbia fatto la pull delle modifiche apportate inerenti a un errore simile di poco tempo fa.

**Comment by AGalassi** [comment]
Ho letto solo ora, adesso controlliamo il codice del server

**Comment by AGalassi** [comment]
A livello di codice mi sembra che la cosa non si dovrebbe verificare, e usando il Tester ottengo fine partita.
Potete provare anche voi se il tester fa completare correttamente la partita o meno?

**Comment by Riccardo-Vasumini** [comment]
Riprovando col tester non mi da problemi, quindi non so cosa abbia scatenato l'errore l'altro giorno, avrò sbagliato qualcosa forse, grazie comunque!
