### ISSUE TITLE
Problema nel nome del giocatore nero

### ISSUE THREAD

**Issue by andre-bisa** [AGalassi/TablutCompetition#9]
Al nome del giocatore nero non viene applicata la funzione di cancellazione dei caratteri invalidi. Nell'esempio allegato la stringa che viene passata è sempre la stessa ma il server li gestisce in maniera diversa.
![Schermata del 2019-05-22 16-58-31](https://user-images.githubusercontent.com/32579482/58185333-2ac42a80-7cb3-11e9-8538-26a887b54040.png)

**Comment by AGalassi** [comment]
Solved!
